# Generated by Django 5.2.17 on 2026-08-20 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import posthog.uuidt


class Migration(migrations.Migration):
    dependencies = [('posthog', '1310_provisioning_rate_limit_overrides'), ('warehouse_sources', '0151_repin_linkedin_ads_api_version'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.AddField(
            model_name="externaldatajob",
            name="watermark_start",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ExternalDataDestination",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted", models.BooleanField(blank=True, default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(default=posthog.uuidt.UUIDT, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PostHogWarehouse", "PostHog warehouse"),
                            ("Redshift", "Redshift"),
                            ("Snowflake", "Snowflake"),
                            ("BigQuery", "BigQuery"),
                            ("Postgres", "Postgres"),
                            ("Databricks", "Databricks"),
                            ("AzureBlob", "Azure Blob"),
                            ("S3", "S3"),
                        ],
                        max_length=64,
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Non-secret shape config: target database/schema/dataset, bucket and prefix, file format.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        help_text="Credentials for this destination. Null for the PostHog warehouse.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="posthog.integration",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="posthog.team"
                    ),
                ),
            ],
            options={
                "db_table": "posthog_externaldatadestination",
            },
        ),
        migrations.CreateModel(
            name="ExternalDataDestinationJob",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(default=posthog.uuidt.UUIDT, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("PostHogWarehouse", "PostHog warehouse"),
                            ("Redshift", "Redshift"),
                            ("Snowflake", "Snowflake"),
                            ("BigQuery", "BigQuery"),
                            ("Postgres", "Postgres"),
                            ("Databricks", "Databricks"),
                            ("AzureBlob", "Azure Blob"),
                            ("S3", "S3"),
                        ],
                        max_length=64,
                    ),
                ),
                ("destination_name", models.CharField(max_length=400)),
                ("config_snapshot", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(max_length=400)),
                ("rows_synced", models.BigIntegerField(blank=True, null=True)),
                ("latest_error", models.TextField(blank=True, null=True)),
                ("billable", models.BooleanField(db_default=True, default=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse_sources.externaldatadestination",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_jobs",
                        to="warehouse_sources.externaldatajob",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="posthog.team"
                    ),
                ),
            ],
            options={
                "db_table": "posthog_externaldatadestinationjob",
            },
        ),
        migrations.CreateModel(
            name="ExternalDataSchemaDestination",
            fields=[
                (
                    "id",
                    models.UUIDField(default=posthog.uuidt.UUIDT, editable=False, primary_key=True, serialize=False),
                ),
                ("enabled", models.BooleanField(db_default=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_links",
                        to="warehouse_sources.externaldatadestination",
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_links",
                        to="warehouse_sources.externaldataschema",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="posthog.team"
                    ),
                ),
            ],
            options={
                "db_table": "posthog_externaldataschemadestination",
            },
        ),
        migrations.CreateModel(
            name="ExternalDataSourceDestination",
            fields=[
                (
                    "id",
                    models.UUIDField(default=posthog.uuidt.UUIDT, editable=False, primary_key=True, serialize=False),
                ),
                ("enabled", models.BooleanField(db_default=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="warehouse_sources.externaldatadestination",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_links",
                        to="warehouse_sources.externaldatasource",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="posthog.team"
                    ),
                ),
            ],
            options={
                "db_table": "posthog_externaldatasourcedestination",
            },
        ),
        migrations.AddIndex(
            model_name="externaldatadestination",
            index=models.Index(fields=["team", "type"], name="wsd_team_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="externaldatadestination",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False), ("type", "PostHogWarehouse")),
                fields=("team",),
                name="wsd_one_warehouse_dest_per_team",
            ),
        ),
        migrations.AddIndex(
            model_name="externaldatadestinationjob",
            index=models.Index(fields=["team", "billable", "status", "finished_at"], name="wsdj_billing_idx"),
        ),
        migrations.AddIndex(
            model_name="externaldatadestinationjob",
            index=models.Index(fields=["job"], name="wsdj_job_idx"),
        ),
        migrations.AddConstraint(
            model_name="externaldatadestinationjob",
            constraint=models.UniqueConstraint(fields=("job", "destination"), name="wsd_job_dest_uniq"),
        ),
        migrations.AddConstraint(
            model_name="externaldataschemadestination",
            constraint=models.UniqueConstraint(fields=("schema", "destination"), name="wsd_schema_dest_uniq"),
        ),
        migrations.AddConstraint(
            model_name="externaldatasourcedestination",
            constraint=models.UniqueConstraint(fields=("source", "destination"), name="wsd_source_dest_uniq"),
        ),
    ]
