import { MakeLogicType, actions, isBreakpoint, kea, key, listeners, path, props, reducers } from 'kea'
import { actionToUrl, router, urlToAction } from 'kea-router'

import { lemonToast } from 'lib/lemon-ui/LemonToast'
import { teamLogic } from 'scenes/teamLogic'
import { urls } from 'scenes/urls'

import { visionObservationsSearchRetrieve } from '../generated/api'
import type { ReplayObservationApi } from '../generated/api.schemas'

// The server's MAX_SEARCH_LIMIT; a larger value would 400.
const SEARCH_RESULT_LIMIT = 50

export interface ObservationSearchLogicProps {
    /** Scope the search to one scanner; null searches every scanner the user can read. */
    scannerId: string | null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface observationSearchLogicValues {
    query: string
    results: ReplayObservationApi[] | null
    searchedQuery: string | null
    searching: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface observationSearchLogicActions {
    search: () => {
        value: true
    }
    searchFailure: () => {
        value: true
    }
    searchSuccess: (
        results: ReplayObservationApi[],
        query: string
    ) => {
        query: string
        results: ReplayObservationApi[]
    }
    setQuery: (query: string) => {
        query: string
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface observationSearchLogicMeta {
    key: any
}

export type observationSearchLogicType = MakeLogicType<
    observationSearchLogicValues,
    observationSearchLogicActions,
    ObservationSearchLogicProps,
    observationSearchLogicMeta
>

export const observationSearchLogic = kea<observationSearchLogicType>([
    path(['products', 'replay_vision', 'frontend', 'search', 'observationSearchLogic']),
    props({} as ObservationSearchLogicProps),
    key((props) => props.scannerId ?? 'cross-scanner'),

    actions({
        setQuery: (query: string) => ({ query }),
        search: true,
        searchSuccess: (results: ReplayObservationApi[], query: string) => ({ results, query }),
        searchFailure: true,
    }),

    reducers({
        query: [
            '' as string,
            {
                setQuery: (_, { query }) => query,
            },
        ],
        // null until the first search, so the empty state can tell "not searched yet" from "no matches".
        results: [
            null as ReplayObservationApi[] | null,
            {
                searchSuccess: (_, { results }) => results,
            },
        ],
        searching: [
            false,
            {
                search: () => true,
                searchSuccess: () => false,
                searchFailure: () => false,
            },
        ],
        searchedQuery: [
            null as string | null,
            {
                searchSuccess: (_, { query }) => query,
            },
        ],
    }),

    listeners(({ actions, props, values }) => ({
        search: async (_, breakpoint) => {
            const query = values.query.trim()
            if (!query) {
                actions.searchFailure()
                return
            }
            const teamId = teamLogic.values.currentTeamId
            if (!teamId) {
                actions.searchFailure()
                return
            }
            try {
                const response = await visionObservationsSearchRetrieve(String(teamId), {
                    q: query,
                    limit: SEARCH_RESULT_LIMIT,
                    ...(props.scannerId ? { scanner_id: props.scannerId } : {}),
                })
                // Drop out-of-order responses; the newest search owns the results.
                breakpoint()
                actions.searchSuccess(response.results ?? [], query)
            } catch (error: any) {
                if (error instanceof Error && isBreakpoint(error)) {
                    throw error
                }
                lemonToast.error(`Search failed${error?.detail ? `: ${error.detail}` : ''}`)
                actions.searchFailure()
            }
        },
    })),

    actionToUrl(({ values }) => ({
        search: () => [
            router.values.location.pathname,
            { ...router.values.searchParams, q: values.query.trim() || undefined },
            router.values.hashParams,
            { replace: true },
        ],
    })),

    urlToAction(({ actions, props, values }) => ({
        [props.scannerId ? urls.replayVision(props.scannerId) : urls.replayVision()]: (_, searchParams) => {
            if (searchParams.tab !== 'search') {
                return
            }
            const raw = searchParams.q
            const q = typeof raw === 'string' ? raw : typeof raw === 'number' ? String(raw) : ''
            // Run a deep-linked query once; re-navigation with the same q keeps the current results.
            if (q && q !== values.searchedQuery) {
                actions.setQuery(q)
                actions.search()
            }
        },
    })),
])
